// English words database for Wordle
// Format: Array of objects with word and definition

const englishWords = [
  {
    palabra: "APPLE",
    definicion: "A round fruit with red, green, or yellow skin and a firm white flesh."
  },
  {
    palabra: "BEACH",
    definicion: "A sandy or pebbly shore by the ocean or a lake."
  },
  {
    palabra: "CLOUD",
    definicion: "A visible mass of condensed water vapor floating in the atmosphere."
  },
  {
    palabra: "DREAM",
    definicion: "A series of thoughts, images, and sensations occurring in a person's mind during sleep."
  },
  {
    palabra: "EARTH",
    definicion: "The planet on which we live; the world."
  },
  {
    palabra: "FLAME",
    definicion: "A hot glowing body of ignited gas that is generated by something on fire."
  },
  {
    palabra: "GRASS",
    definicion: "Vegetation consisting of typically short plants with long, narrow leaves."
  },
  {
    palabra: "HOUSE",
    definicion: "A building for human habitation, especially one that is lived in by a family."
  },
  {
    palabra: "LIGHT",
    definicion: "The natural agent that stimulates sight and makes things visible."
  },
  {
    palabra: "MUSIC",
    definicion: "Vocal or instrumental sounds combined in such a way as to produce beauty of form."
  },
  {
    palabra: "NIGHT",
    definicion: "The period of darkness in each twenty-four hours; the time from sunset to sunrise."
  },
  {
    palabra: "OCEAN",
    definicion: "A very large expanse of sea, in particular each of the main areas into which the sea is divided."
  },
  {
    palabra: "PIANO",
    definicion: "A large keyboard musical instrument with a wooden case enclosing a soundboard and metal strings."
  },
  {
    palabra: "QUEEN",
    definicion: "The female ruler of an independent state, especially one who inherits the position by right of birth."
  },
  {
    palabra: "RIVER",
    definicion: "A large natural stream of water flowing in a channel to the sea, a lake, or another such stream."
  },
  {
    palabra: "STORM",
    definicion: "A violent disturbance of the atmosphere with strong winds and usually rain, thunder, lightning, or snow."
  },
  {
    palabra: "TABLE",
    definicion: "A piece of furniture with a flat top and one or more legs, providing a level surface for eating, writing, or working."
  },
  {
    palabra: "UNCLE",
    definicion: "The brother of one's father or mother or the husband of one's aunt."
  },
  {
    palabra: "VOICE",
    definicion: "The sound produced in a person's larynx and uttered through the mouth, as speech or song."
  },
  {
    palabra: "WATER",
    definicion: "A colorless, transparent, odorless liquid that forms the seas, lakes, rivers, and rain."
  },
  {
    palabra: "YOUTH",
    definicion: "The period between childhood and adult age."
  },
  {
    palabra: "ZEBRA",
    definicion: "An African wild horse with black-and-white stripes and an erect mane."
  },
  {
    palabra: "BREAD",
    definicion: "Food made of flour, water, and yeast or another leavening agent, mixed together and baked."
  },
  {
    palabra: "CHAIR",
    definicion: "A separate seat for one person, typically with a back and four legs."
  },
  {
    palabra: "DANCE",
    definicion: "Move rhythmically to music, typically following a set sequence of steps."
  },
  {
    palabra: "FRUIT",
    definicion: "The sweet and fleshy product of a tree or other plant that contains seed and can be eaten as food."
  },
  {
    palabra: "GREEN",
    definicion: "Of the color between blue and yellow in the spectrum; colored like grass or emeralds."
  },
  {
    palabra: "HEART",
    definicion: "A hollow muscular organ that pumps the blood through the circulatory system by rhythmic contraction and dilation."
  },
  {
    palabra: "JUICE",
    definicion: "The liquid obtained from or present in fruit or vegetables."
  },
  {
    palabra: "KNIFE",
    definicion: "An instrument composed of a blade fixed into a handle, used for cutting or as a weapon."
  },
  {
    palabra: "LEMON",
    definicion: "A pale yellow oval citrus fruit with thick skin and fragrant, acidic juice."
  },
  {
    palabra: "MOUSE",
    definicion: "A small rodent that typically has a pointed snout, relatively large ears and eyes, and a long tail."
  },
  {
    palabra: "PHONE",
    definicion: "A system for transmitting voices over a distance using wire or radio, by converting acoustic vibrations to electrical signals."
  },
  {
    palabra: "SMILE",
    definicion: "Form one's features into a pleased, kind, or amused expression, typically with the corners of the mouth turned up."
  },
  {
    palabra: "TRAIN",
    definicion: "A series of connected railway carriages or wagons moved by a locomotive."
  },
  {
    palabra: "WATCH",
    definicion: "Look at or observe attentively over a period of time."
  },
  {
    palabra: "BIRDY",
    definicion: "A small bird (informal)."
  },
  {
    palabra: "SPACE",
    definicion: "A continuous area or expanse which is free, available, or unoccupied."
  },
  {
    palabra: "GREAT",
    definicion: "Of an extent, amount, or intensity considerably above the normal or average."
  },
  {
    palabra: "WORLD",
    definicion: "The earth, together with all of its countries, peoples, and natural features."
  }
];

// 5-letter words for the Wordle game
const palabrasWordle = englishWords.filter(item => item.palabra.length === 5);

// Export words for use in the game
export { palabrasWordle, englishWords as palabrasUruguayas };
