--no-warnings
--ignore-errors
--no-check-certificate
--format bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best
--socket-timeout 180
--force-ipv4
--geo-bypass
--no-cookies
--no-cache-dir
--no-progress
--add-header "User-Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Mobile Safari/537.36"
--add-header "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8"
--add-header "Accept-Language: es-ES,es;q=0.9,en;q=0.8"
--extractor-retries 5
--fragment-retries 5
--retry-sleep 5
--throttled-rate 100K
--buffer-size 16K
--max-filesize 2G
--max-downloads 1
--abort-on-error