# Configuración general
--no-warnings
--ignore-errors
--no-check-certificate
e --verbose

# Formato de video
--format bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best

# Configuración de red y anti-bot
--socket-timeout 120
--force-ipv4
--geo-bypass
--proxy ""
--sleep-interval 3
--max-sleep-interval 8
--sleep-subtitles 2
--extractor-retries 10
--cookies "cookies.txt"
--referer "https://www.youtube.com/"
--add-header "Upgrade-Insecure-Requests: 1"
--add-header "Sec-Fetch-Site: none"
--add-header "Sec-Fetch-Mode: navigate"
--add-header "Sec-Fetch-User: ?1"
--add-header "Sec-Fetch-Dest: document"

# Configuración de User-Agent y cookies
--user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
--add-header "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"
--add-header "Accept-Language: es-ES,es;q=0.9,en;q=0.8"
--add-header "DNT: 1"
--add-header "Connection: keep-alive"
--cookies-from-browser chrome
--mark-watched